# Description
# ===========
# This playbook creates 
# - An Azure Linux Web app with Java container Tomcat 8.5.
# - An Azure Traffic manager profile.
# - Add the web site created as an endpoint of the Traffic Manager Profile.
#
# This playbook requires Ansible version >=2.7, or you could use role azure.azure_preview_modules
# If you're using Ansible >=2.7, just remove the role lines.

- hosts: localhost
  connection: local
  vars:
    app_name: myTestApp
    location: eastus
    linux_plan_name: myTestPlan
    traffic_manager_profile_name: myTMProfile
    traffic_manager_endpoint_name: endpoint1

  tasks:
  - name: terraform set up
    terraform:
        project_path: 'https://github.com/venkateshwj/ansible_tower/tree/master/terraform'
        state: "present"
        force_init: true
        backend_config:
          arm_subscription_id: "{{ arm_subscription_id }}"
          arm_client_id: "{{ arm_client_id }}"
          arm_client_secret: "{{ arm_client_secret }}"
          arm_tenant_id: "{{ arm_tenant_id }}"
          resource_group_name: "{{ resource_group_name }}"
          storage_account_name: "{{ storage_account_name }}"
          container_name: "{{ container_name }}"
          key: "{{ app_name }}"
