# Description
# ===========
# This playbook creates 
# - An Azure Linux Web app with Java container Tomcat 8.5.
# - An Azure Traffic manager profile.
# - Add the web site created as an endpoint of the Traffic Manager Profile.
#
# This playbook requires Ansible version >=2.7, or you could use role azure.azure_preview_modules
# If you're using Ansible >=2.7, just remove the role lines.

- hosts: localhost
  connection: local
  vars:
    app_name: myTestApp
    location: eastus
    linux_plan_name: myTestPlan
    traffic_manager_profile_name: myTMProfile
    traffic_manager_endpoint_name: endpoint1

  tasks:
  - name: Create App Service Plan
    azure_rm_appserviceplan:
      resource_group: "{{ resource_group_name }}"
      name: "{{ linux_plan_name }}"
      location: "{{ location }}"
      is_linux: true
      sku: S1
      number_of_workers: 1

  - name: Create a Linux web app with Java framework and Tomcat
    azure_rm_webapp:
      resource_group: "{{ resource_group_name }}"
      name: "{{ app_name }}"
      plan:
        resource_group: "{{ resource_group_name }}"
        name: "{{ linux_plan_name }}"
      app_settings:
        testkey: "testvalue"
      frameworks:
        - name: java
          version: 8
          settings:
            java_container: "Tomcat"
            java_container_version: "8.5"

  - name: Get web app facts
    azure_rm_webapp_facts:
      resource_group: "{{ resource_group_name }}"
      name: "{{ app_name }}"
      return_publish_profile: true
    register: webapp